export const SERVER_URL = 'http://localhost:3000';
export const GET_FEATURED_RECIPES_URI = '/featured-recipes';
export const SEARCH_URI ='/search';
export const RECIPE_URI = '/recipes';
export const REGISTER_URI = '/auth/register';
export const LOGIN_URI = '/auth/login';
export const USER_BOOKMARK_URI = '/user/bookmarks/get';
export const ADD_BOOKMARK_URI = '/user/bookmarks/add';
export const DELETE_USER_URI = '/user/delete';